# Generated by Django 3.1.7 on 2021-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1222, null=True)),
                ('AccountNo', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='CurrentBalance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
