# Generated by Django 3.1.7 on 2021-04-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210412_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SenderName', models.CharField(max_length=122, null=True)),
                ('SenderAccountNo', models.CharField(max_length=122, null=True)),
                ('ReceiverName', models.CharField(max_length=122, null=True)),
                ('ReceiverAccountNo', models.CharField(max_length=122, null=True)),
                ('Amount', models.IntegerField(null=True)),
            ],
        ),
    ]
