# Generated by Django 3.1.7 on 2021-04-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
