# Generated by Django 3.1.7 on 2021-04-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210417_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer_money',
            old_name='RecieverAccountNo',
            new_name='ReceiverAccountNo',
        ),
    ]
