# Generated by Django 3.1.7 on 2021-04-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210419_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_money',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
