# Generated by Django 3.1.7 on 2021-04-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210420_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_money',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
