# Generated by Django 3.1.7 on 2021-04-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210420_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer_money',
            old_name='ReceiverAccountNo',
            new_name='RecieverAccountNo',
        ),
        migrations.RenameField(
            model_name='transfer_money',
            old_name='ReceiverName',
            new_name='RecieverName',
        ),
    ]
