# Generated by Django 3.1.7 on 2021-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_transfer_money_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_money',
            name='Amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
