# Generated by Django 3.1.7 on 2021-04-20 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20210420_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_money',
            name='Amount',
            field=models.IntegerField(default=datetime.datetime(2021, 4, 20, 13, 32, 54, 702707, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
