# Generated by Django 3.1.7 on 2021-04-20 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20210420_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_money',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 13, 49, 18, 758372, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
